### ISSUE TITLE
correlation between actuator linear vs slope

### ISSUE THREAD

**Issue by cherryphilip74** [Berg0162/simcline#3]
Dear Jörgen!

I'm back again with a couple questions. First I tried to study the simcline  flowchart just to adopt it on my chassis.
I understood the correlation between counts / slope % / VL6180 reads height to target /height of the fork wheel from gound.

I adopted these concepts also on my chassis (aluminum + 3d printed abs) just to create a simple solution without wood.
In general it works well, the flat position is correct but when slope value increases above 3.2% the equipment is not alligned with the software of the trainer.

Inside spreadsheet you can find all values related to VL6180 readings, slopes and wheel support to ground height.

Could you tell me what I'm doing wrong?

Thanks angan for your answers

Best Regards
Filippo

[SimCline.xlsx](https://github.com/Berg0162/simcline/files/7763674/SimCline.xlsx)
 
![20211222_130815](https://user-images.githubusercontent.com/19619650/147118767-877ccd02-dc21-4fc7-a008-25df31e8fb89.jpg)
![20211222_130828](https://user-images.githubusercontent.com/19619650/147118770-c8d4c6df-e41a-494b-8b1a-f804158e9ac8.jpg)

![20211222_125421](https://user-images.githubusercontent.com/19619650/147118747-e6536195-f3d1-41ed-a599-5b5ccb7c2182.jpg)
![20211222_125426](https://user-images.githubusercontent.com/19619650/147118752-3f4b834c-6841-46a2-a65f-177c62cba2c8.jpg)

![20211222_130547](https://user-images.githubusercontent.com/19619650/147118760-22fcfa1f-17e7-4847-bde5-ce385a40c68d.jpg)
![20211222_130554](https://user-images.githubusercontent.com/19619650/147118765-4238b0c2-d225-4eed-a094-6675200ef98a.jpg)

![20211222_130536](https://user-images.githubusercontent.com/19619650/147118756-1b948817-b8f1-4a62-a36e-640ab01d956f.jpg)
![20211222_130838](https://user-images.githubusercontent.com/19619650/147118774-b3493c48-b73e-4ce1-a3a2-86ead1c2c0c9.jpg)
![20211222_130843](https://user-images.githubusercontent.com/19619650/147118775-d6274587-7af2-4b3c-9cbe-726b48fee82d.jpg)
![20211222_130902](https://user-images.githubusercontent.com/19619650/147118777-d8893630-7161-4c92-8539-7fc2fff79e31.jpg)
![20211222_130909](https://user-images.githubusercontent.com/19619650/147118778-ebd6fc01-880f-461d-9ec1-1f9a15237e73.jpg)

**Comment by cherryphilip74** [comment]
Update 
With TACX Trainer App it works fine between -5% and 16%, simcline monitor showing the same slope indicated on screen desktop, while with Rouvy App after 5% I observed a misalignment. I will try also Zwift app soon

**Comment by Berg0162** [comment]
It is impossible for me to comment on these values since I have no inside knowledge of your construction and/or software... Which components have been applied? Is the Time-of-Flight sensor (short or long distance type?) carefully aligned? How is the code modified? What code settings are you applying? Etcetera. 
I have a suggestion: please have a look at this: https://github.com/Berg0162/simcline/blob/master/README.md#simcline-in-tts4-controlled-operation
The training apps you have operational might very well be not WYSIWYG!

I compliment you with your mechanical design, it really looks robust. Have fun with it! Many nice indoor rides!

**Comment by cherryphilip74** [comment]
Dear Jörgen!
Yes, i changed some values in according to my climb equipment.
I'm happy to share with all community my design (2 versions, the first with 250mm actuator linear and the other one of 300mm).
I used all components listed on your main page of simcline project, but i made also a specific pcb with leds and push button reset (i would like to make a complete board with motor driver included), see picture below.
![image](https://user-images.githubusercontent.com/19619650/147493525-2d7aa6cf-a833-4bf0-a379-a549ebad2a7c.png)

Here some details:

RGVMAX, RGVMIN, aRGVmax e aRGVmin values parameters:
![image](https://user-images.githubusercontent.com/19619650/147493676-c5890c12-e5f3-473a-a809-e01e9a2c59c3.png)

Maximun extension with hardware stopping:
![image](https://user-images.githubusercontent.com/19619650/147493894-ed592e97-b92e-4b36-a495-bff071faf15b.png)

iMax & iMin map:
![image](https://user-images.githubusercontent.com/19619650/147494085-20197ff7-713d-4f5f-973b-5584519394c2.png)

aRGVmax & aRGVmin map:
![image](https://user-images.githubusercontent.com/19619650/147494152-27e581ef-28af-45bc-8977-17270dccefe9.png)

Excel table based on the parameters set above:
![image](https://user-images.githubusercontent.com/19619650/147496366-da2fc763-081d-407f-8f66-9ed37e233bdd.png)

Heights fork wheel to ground (max, flat and min height):
![image](https://user-images.githubusercontent.com/19619650/147497344-7d605de2-7283-4dbc-87da-4bb5b2e70112.png)

details about board and VL6180X sensor
![image](https://user-images.githubusercontent.com/19619650/147497613-a1470769-a0be-452f-9dbb-ccde3f8b9b7a.png)

Hardware tested with:
BKOOL --> Its ok
TACX --> its ok 
ROUVY --> Not ok, disalligment 
here some pictures:


![20211227_125225](https://user-images.githubusercontent.com/19619650/147497779-3c0beae7-3e88-4593-84e4-b51d6505f22f.jpg)

![20211227_124857](https://user-images.githubusercontent.com/19619650/147497792-755cd893-c959-4f08-855d-7ad1f1bb194b.jpg)

![20211227_123846](https://user-images.githubusercontent.com/19619650/147497868-8910263c-4707-476a-9fc6-44fffc669c66.jpg)

![20211227_123343](https://user-images.githubusercontent.com/19619650/147497823-99309d6b-3f5a-424c-a9b3-f8cf5a6f7823.jpg)

Let me know if I have done something wrong and if so what to correct.

Best Regards
Filippo

**Comment by GrepNatural** [comment]
Dear Filippo

in short, the ROUVY does not send the same values from the application about the gradient into the trainer. I have asked them and they do not say if is truth or not, becuase of company policy.

 there is my summary of the findings:

- TACX application very preciselly sets  incline/decline values on the SimCline and the values set in the application are set immediatelly also on the SimCline.

- Zwift has the incline/decline value shown in integer, so we cannot speak about precize setting of the incline/decline value from rider point of view, but the incline value approximattely corresponds what is set/shown on the SimCline.
But! the Zwift decline value is unexpetidly devided by 2! Thi is confirmed also by my colleague with Wahoo Climb device.
What I also noticed in the Zwift, that the SimCline response on change of the gradient in the application is very slow. I would guess that Zwift is sending the value delayed.
I did all the test on 'Alpe du Zwift' ride.

- ROUVY sets the values up to +/- 4% the same also on SimCline but then the values do not significantly corresponds. Eg. with 10% shown in the ROUVY application, the SimCline is set only to 8% and for 13% is there only aprox 10% set.
The advantage of Rouvy is that the values are changed fluently and quickly and the values are shown in 1/10 of %

I am very surprise that both the applications do not set the gradient to the trainer equally with what is shown to the rider.
I have asked my colleague to check my findings with Wahoo Climb on the ROUVY as well.

Thanks Martin

**Comment by cherryphilip74** [comment]
Hi Martin,
your feedback is reassuring to me. I too find the same values with Rouvy, 10% set in the ROUVY application, the SimCline shows only 8% and for 11% it is only show to about 8.5%. This is valid only incline positive, in decline it seems aligned (tested up to -3.5%).
Yesterday and today, I've tested:

•	TACX application, I confirm that it's very precisely sets incline/decline values on the SimCline and the values set in the application are set immediately also on the SimCline

•	BKOOL application, also this application seems very precisely and having same TACX app characterizes.

It took me a long time just to find the correct setting and I understood later that a possible issue could be associated with the Rouvy app.
I think that i find the right setup for my hardware, I will do other tests with BKOOL and TACX only and then will be release the project on my github/cherryphilip74 for the community.
I big thanks to Jörgen for this opportunity and for the patience for the countless messages.

Best Regards
Filippo

**Comment by wells240** [comment]
Nice work Filippo 
I'm also working on Simclin project.
I keep Jörgen very busy :) He is a great help and I appreciate it very much.

**Comment by Berg0162** [comment]
Dear Filippo,
I have carefully looked at how you have modified some of the critical settings in the Simcline code to suit your setup. I do not see any irregularities or inconsistencies that should bother you or disturb a smooth working of the code. None of these settings can be responsible for the discrepancies that you (and many others) came across with respect to WYSIWYG for road inclination!
By the way nice clean solution with that PCB, compliments! What software have you used for the PCB design and where did you have it produced?
Best wishes,
Jörgen.

**Comment by wells240** [comment]
Jörgen,
This mail was not for me

**Comment by Berg0162** [comment]
You are right but you are a member now of this thread and you will see all comments..... that is a feature not a bug!

**Comment by cherryphilip74** [comment]
> Dear Filippo, I have carefully looked at how you have modified some of the critical settings in the Simcline code to suit your setup. I do not see any irregularities or inconsistencies that should bother you or disturb a smooth working of the code. None of these settings can be responsible for the discrepancies that you (and many others) came across with respect to WYSIWYG for road inclination! By the way nice clean solution with that PCB, compliments! What software have you used for the PCB design and where did you have it produced? Best wishes, Jörgen.

Dear Jörgen!

thanks for your feedback. 
I confirm that my hardware with TACX and BKOOL respects the WYSIWYG  rule (error within +/- 2-3mm sometimes also no error).

Regarding to PCB design, i use [easyeda](https://easyeda.com/editor) the suite complete for design (easyeda)/manufactuing (JLPCB) and components (LCSC). It's possible to produce assembled or pre-assembled PCBs.

If you want I can be happy to help you with the design (this is my job) or to take the first steps (here my email cherryphilip@email.com)

For me this trend may be closed 

Best wishes,
Filippo
