### ISSUE TITLE
Support for other than Feather nRF52840 processors

### ISSUE THREAD

**Issue by Berg0162** [Berg0162/simcline#6]
Have you considered using a D1 Mini NodeMCU ESP32 WiFi and Bluetooth BLE? 
Link here: https://amzn.eu/d/2XgwXKY

ESP32 and nRF52 can do WiFi, Bluetooth Classic, and Bluetooth Low Energy (BLE), so seem are equivalent.
Are there technical limitation can't be applied to ESP32?
ESP32 is cheaper than nRF2 also low dimension

Best Regards
Filippo

_Originally posted by @cherryphilip74 in https://github.com/Berg0162/simcline/issues/5#issuecomment-1338824386_

**Comment by Berg0162** [comment]
When I started the Simcline project (3 years ago),  I was looking for a processor that had ANT+ and excellent BLE support. The Adafruit support is great, with lots of code samples and a very rich library for a wide range of sensors. The Feather nRF52832 (Nordic Silicon chip) was offering the right specs. , Adafruit a quick start and steep learning curve!
Unfortunately installing the Nordic Softdevice (firmware) for ANT+ was a bridge to far for me, so I decided to go for the BLE solution and (ANT+) FE-C over BLE that is supported by TACX. At this very moment this is still working without any flaws at my home (3 times a week during indoor season). The Feather type one should buy now is a nRF52840 (more value for money) and what is more: lots of memory. The MITM implementation is at the limits of what this processor can offer due to the large throughput of the BLE channels: never miss a packet (from the trainer of Zwift) or you are down!
Later developments benefitted of the code base that I developed (after all, the cost for an IT-development project is not the processor ($24)  but the development speed of the programmer (hourly salary >$50). The FTMS enabled code development took so far more than 80 hours (!), that is low because I could reuse a lot of code from the Wahoo Sim project and the original TACX Simcline.
Yes I have been looking at other processors but a few bucks more or less is not the issue here: supplier support (installed software base), reuse of code and platform continuity are determining whether the projects are feasible and successful or not... 
I am considering an ESP32 board now (Adafruit has an interesting Feather with ESP32) for future IOT projects, only because of its WIFI support. Notice that the Simcline code projects can be ported to the ESP32 platform at the cost of many hours... that I rather spent exploring new things! At the start of such an enterprise one is not sure at all, that the ESP32 is as powerful on Bluetooth, as the proven Nordic chip, when it comes to handling a heavy duty BLE MITM application!

**Comment by macrocd** [comment]
I almost finish to assemble my Simcline 2.0. I Used Adafruit-ItsyBitsy-nRF52840 And SH1106 Oled display. Usually I use Rouvy+ Elite SUITO Trainer.  I'm waiting for 3D printing parts to terminate my setup. 
Implementing the itsybitsy board is almost immediate. For the Display I took a little more time because I don't know the platform well.
M.

**Comment by Berg0162** [comment]
Great! 
Best wishes, Jörgen

**Comment by Berg0162** [comment]
I have been working recently on porting the nRF52 platform Simcline code, (supporting FTMS-enabled trainers), to the ESP32 platform. I have applied an Adafruit product called Huzzah 32 ([Feather-esp32-V2](https://learn.adafruit.com/adafruit-esp32-feather-v2) to remain compatible with the Feather formfactor, to allow an easy application of the board in my Simcline 2.0 design/construction.
The process was not easy since the Adafruit/Bluefruit BLE libraries turned out to be superior over the default ESP32 Bluedroid implementation. ESP32 Bluedroid is buggy when the BLE implementation becomes more demanding than a simple single Client or single Server, as is clearly the case with BLE MITM. 
Adafruit/Bluefruit on nRF52 was loaded to its limits with the FTMS supporting BLE MITM code but kept working, in the case of ESP32 Bluedroid the implementation was somewhat to demanding.... So just comparing the overal specs (on paper) of both processor platforms is not sufficient... one needs to take into account the (quality of the) available libraries as well to reach success.
Fortunately H2Zero has created a more or less compatible replacement for Bluedroid, called NimBLE [H2Zero NimBLE](https://h2zero.github.io/NimBLE-Arduino/index.html)! The application of NimBLE saved the porting project! So it looks now that we will be able to benefit of the immense specs of the ESP32 platform after all!
I will upload soon the ESP32 Simcline code for FTMS-enabled trainers and give you, ESP32 adepts, a change to test for yourself!
Best wishes,
Jörgen.

PS macrocd, how are you doing? Have you succeeded? Can you share your experience?

**Comment by Berg0162** [comment]
Dear M,
Thank you for your update!
Definitely no changes with respect to the display in version 2.1. Compare and check your inserted SH1106 settings of version 011 vs 2.1...

**Comment by Berg0162** [comment]
Client, Server and Bridge 1.0 versions for ESP32 platform have been uploaded now!

**Comment by cherryphilip74** [comment]
I will test it tomorrowSent from Android deviceIl 26 feb 2023 11:41, Jörgen van den Berg ***@***.***> ha scritto:
Client, Server and Bridge 1.0 versions for ESP32 platform have been uploaded now!

**Comment by Berg0162** [comment]
Dear Filippo,
I am curious to hear from you about your experiences with the ESP32 code.....
Best wishes,
Jörgen.
